[package]
name = "moon_task_runner"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "System for running tasks."
homepage = "https://moonrepo.dev/moon"
repository = "https://github.com/moonrepo/moon"
publish = false

[dependencies]
moon_api = { path = "../api" }
moon_action = { path = "../action" }
moon_action_context = { path = "../action-context" }
moon_cache = { path = "../cache" }
moon_cache_item = { path = "../cache-item" }
moon_common = { path = "../common" }
moon_config = { path = "../config" }
# TODO remove
moon_platform = { path = "../../crates/core/platform" }
moon_platform_runtime = { path = "../platform-runtime" }
moon_process = { path = "../process" }
moon_project = { path = "../project" }
moon_task = { path = "../task" }
moon_workspace = { path = "../workspace" }
miette = { workspace = true }
serde = { workspace = true }
starbase_archive = { workspace = true }
starbase_utils = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
